#
# Coded by: VirtusDevelops (NeutralPlasma, Gasper Lukman)
#
# MYSQL hasn't been tested so if you find any bugs report them on discord.
#
system:
  dropChance: 10.0 # Drop chance upon breaking grass / tallgrass for crop seed drop to be called
  duplication: true # ability for seed to be duplicated when broken fully grown.
  dropSeeds: false # drop seeds on floor if player inventory is full.


database:
  ip: ""
  port: ""
  name: ""
  user: ""
  password: ""
  useSSL: false
  useMYSQL: false