#
# Coded by: VirtusDevelops (NeutralPlasma, Gasper Lukman)
#
# MYSQL hasn't been tested so if you find any bugs report them on discord.
#
system:
  dropChance: 10.0
  duplication: true # ability for seed to be duplicated when broken fully grown.


database:
  ip: ""
  port: ""
  name: ""
  user: ""
  password: ""
  useSSL: false
  useMYSQL: false